select sysdate from dual;

DROP TABLE CAMPAIGN_CLIENTE;
DROP TABLE CLIENT_OFFER;
DROP TABLE OFFER_VERIFICATION;
DROP TABLE OFFER;
DROP TABLE VERIFICATION;
DROP TABLE CLIENTE;
DROP TABLE CAMPAIGN;
DROP TABLE USUARIO;


CREATE TABLE USUARIO(
    COD_USER NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    CORREO VARCHAR2(60),
    PASSW VARCHAR2(20),
    AREA NUMBER(1)
);

select * from usuario;

CREATE TABLE CAMPAIGN(
    CAMPAIGN_ID NUMBER(2) PRIMARY KEY,
    NOMBRE_CAMPAIGN VARCHAR2(32),
    PRESUPUESTO NUMBER(10),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    PLAN_ACCION VARCHAR2(100),
    KPI_REAL NUMBER (10),
    KPI_OBJETIVO NUMBER (10),
    CODIGO_CRM REFERENCES USUARIO
);

SELECT * FROM CAMPAIGN;


CREATE TABLE CLIENTE(
    CLIENT_DNI NUMBER(8) PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR2(100),
    DIRECCION VARCHAR2(32),
    TELEFONO VARCHAR2(32),
    CORREO VARCHAR(100),
    FECHA_NAC DATE,
    INGRESOS NUMBER(10),
    SCORE_CREDITICIO NUMBER(3)
    
);



select * from cliente;

CREATE TABLE CAMPAIGN_CLIENTE(
    CAMPAIGN_ID REFERENCES CAMPAIGN NOT NULL,
    CLIENT_DNI REFERENCES CLIENTE NOT NULL,
    PRIMARY KEY(CAMPAIGN_ID, CLIENT_DNI),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

select * from campaign_cliente;

select * from usuario u inner join campaign c on u.cod_user = c.codigo_crm ;

select c.*, ca.nombre, ca.campaign_id, ca.plan_accion, ca.presupuesto from campaign_cliente cc inner join cliente c on cc.client_dni = c.client_dni inner join campaign ca on cc.campaign_id = ca.campaign_id;


CREATE TABLE VERIFICATION(
    VERIFICATION_CODE NUMBER(8) PRIMARY KEY,
    DESCRIPCION VARCHAR2(32),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ESTADO NUMBER(1),
    SUGERENCIA VARCHAR2(50),
    CODIGO_ADVISOR REFERENCES USUARIO NOT NULL
);

select * from verification;

CREATE TABLE OFFER(
    CODIGO_OFERTA NUMBER(10) PRIMARY KEY,
    MONTO NUMBER(10),
    PLAZO NUMBER(2),
    ESTADO NUMBER(1),
    TASA NUMBER(4,2),
    EVENTO NUMBER(1),
    CAMPAIGN_ID REFERENCES CAMPAIGN
);

select * from offer;

CREATE TABLE OFFER_VERIFICATION(
    CODIGO_OFERTA REFERENCES OFFER, 
    CODIGO_VERIFICACION REFERENCES VERIFICATION,
    PRIMARY KEY (CODIGO_OFERTA,CODIGO_VERIFICACION)
);

select * from offer_verification;



CREATE TABLE CLIENT_OFFER(
    CLIENT_DNI REFERENCES CLIENTE NOT NULL,
    CODIGO_OFERTA REFERENCES OFFER NOT NULL,
    PRIMARY KEY(CLIENT_DNI, CODIGO_OFERTA)
);

SELECT O.CODIGO_OFERTA, C.CLIENT_DNI, C.SCORE_CREDITICIO, C.INGRESOS, O.PLAZO, O.MONTO, O.TASA FROM CLIENT_OFFER CO INNER JOIN CLIENTE C ON CO.CLIENT_DNI = C.CLIENT_DNI INNER JOIN OFFER O ON CO.CODIGO_OFERTA = O.CODIGO_OFERTA;

SELECT O.CODIGO_OFERTA, C.CLIENT_DNI, C.SCORE_CREDITICIO, C.INGRESOS, O.PLAZO, O.MONTO, O.TASA, 'Plazo: ' || O.PLAZO  || ' Monto: ' || O.MONTO || ' Tasa: ' || O.TASA AS OFERTA
FROM CLIENT_OFFER CO 
INNER JOIN CLIENTE C 
ON CO.CLIENT_DNI = C.CLIENT_DNI 
INNER JOIN OFFER O 
ON CO.CODIGO_OFERTA = O.CODIGO_OFERTA;

select * from client_offer;
